pipeline {
    agent any
    
    tools {
        nodejs 'NodeJS'
    }
    
    environment {
        REGISTRY = 'ghcr.io'
        IMAGE_NAME = 'ALalejandra/proyecto1'
    }
    
    stages {
        stage('Prepare') {
            steps {
                dir('proyecto1') {
                    echo '⚙️ Validando comandos disponibles...'
                    sh 'node --version'
                    sh 'npm --version'
                }
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir('proyecto1') {
                    echo '📥 Instalando dependencias de la app...'
                    sh 'npm install'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('proyecto1') {
                    echo '🧪 Ejecutando pruebas del proyecto...'
                    sh 'npm test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo '🐳 Construyendo imagen Docker desde la subcarpeta...'
                sh 'docker build -t ghcr.io/alalejandra/proyecto1:latest proyecto1/'
            }
        }
    }
    
    post {
        success {
            echo '🎉 ¡Felicidades! El pipeline se ejecutó y construyó la imagen con éxito.'
        }
        failure {
            echo '❌ El pipeline tuvo un fallo, revisa los logs.'
        }
    }
}